BEGIN;

CREATE TABLE IF NOT EXISTS "SIGERSA"."COMPROBANTE_RECUPERACION" (
    id uuid PRIMARY KEY,
    usuario_id uuid NOT NULL,
    expira_en timestamptz NOT NULL,
    usado_en timestamptz NULL,
    creado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_COMPROBANTE_RECUPERACION_USUARIO" FOREIGN KEY (usuario_id)
        REFERENCES "SIGERSA"."USUARIO" (id),
    CONSTRAINT "CK_COMPROBANTE_RECUPERACION_EXPIRACION" CHECK (expira_en > creado_en),
    CONSTRAINT "CK_COMPROBANTE_RECUPERACION_USO" CHECK (usado_en IS NULL OR usado_en >= creado_en)
);

CREATE INDEX IF NOT EXISTS "IX_COMPROBANTE_RECUPERACION_USUARIO_EXPIRA"
    ON "SIGERSA"."COMPROBANTE_RECUPERACION" (usuario_id, expira_en);

COMMIT;
