BEGIN;

SET LOCAL TIME ZONE 'UTC';
SET LOCAL search_path = pg_catalog;

ALTER TABLE "SIGERSA"."SUBCATEGORIA_ALIMENTO"
    ALTER COLUMN nombre TYPE varchar(250);

INSERT INTO "SIGERSA"."CATEGORIA_ALIMENTO" (codigo, nombre, orden, fuente, activo)
SELECT value.codigo, value.nombre, value.orden,
       'Categorías, subcategoría y riesgo microbiológico.xlsx', true
FROM (VALUES
    ('CAT-01', 'Productos lácteos', 1),
    ('CAT-02', 'Grasas y aceites y emulsiones grasas', 2),
    ('CAT-03', 'Hielos comestibles incluidos sorbetes', 3),
    ('CAT-04', 'Frutas y Hortalizas', 4),
    ('CAT-05', 'Confitería', 5),
    ('CAT-06', 'Cereales y productos a base de cereales, derivados de granos de cereales, de raíces y tubérculos, legumbres, leguminosas y médula o corazón blando de palmera, excluidos los productos de panadería', 6),
    ('CAT-07', 'Productos de panadería', 7),
    ('CAT-08', 'Carne y productos cárnicos, incluidos los de aves de corral y Pescados y productos pesqueros', 8),
    ('CAT-09', 'Huevos y productos a base de huevo', 9),
    ('CAT-10', 'Edulcorantes, incluida la miel', 10),
    ('CAT-11', 'Sales, especias, sopas, salsas, y productos proteínicos', 11),
    ('CAT-12', 'Productos alimenticios para usos nutricionales especiales', 12),
    ('CAT-13', 'Bebidas alcohólicas y no alcohólicas, excluidos los productos lácteos', 13),
    ('CAT-14', 'Aperitivos listos para el consumo', 14),
    ('CAT-15', 'Alimentos preparados', 15),
    ('CAT-16', 'Postres', 16),
    ('CAT-17', 'Pescado y productos pesqueros, incluidos moluscos, crustáceos y equinodermos', 17)
) AS value(codigo, nombre, orden)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO "SIGERSA"."SUBCATEGORIA_ALIMENTO"
    (categoria_alimento_id, codigo, nombre, nivel_riesgo, orden, fuente, activo)
SELECT category.id, value.codigo, value.nombre, value.nivel_riesgo, value.orden,
       'Categorías, subcategoría y riesgo microbiológico.xlsx', true
FROM (VALUES
    ('CAT-01', 'SUB-002', 'Productos lácteos líquidos no fermentados, proceso de pasteurización y UHT', 1, 2),
    ('CAT-01', 'SUB-006', 'Productos lácteos fermentados', 1, 6),
    ('CAT-01', 'SUB-007', 'Grasa láctea', 1, 7),
    ('CAT-01', 'SUB-008', 'Queso fresco pasteurizado (madurado menos menos de 60 días)', 2, 8),
    ('CAT-01', 'SUB-009', 'Queso madurado pasteurizado (madurado más de 60 días)', 1, 9),
    ('CAT-01', 'SUB-010', 'Queso elaborado, fundido, procesado', 1, 10),
    ('CAT-01', 'SUB-011', 'Queso fresco pasteurizado (con ingredientes añadidos)', 2, 11),
    ('CAT-01', 'SUB-012', 'Productos lácteos en polvo', 1, 12),
    ('CAT-01', 'SUB-013', 'Helados', 1, 13),
    ('CAT-01', 'SUB-014', 'Dulces', 1, 14),
    ('CAT-01', 'SUB-015', 'Mantequilla no pasteurizada', 3, 15),
    ('CAT-01', 'SUB-016', 'Queso fresco no pasteurizado', 3, 16),
    ('CAT-01', 'SUB-017', 'Queso madurado (>60 días ) no pasteurizado', 2, 17),
    ('CAT-02', 'SUB-018', 'Grasas y aceites (aw muy baja: <0.6)', 1, 18),
    ('CAT-02', 'SUB-019', 'Emulsiones grasas, principalmente del tipo agua en aceite', 1, 19),
    ('CAT-02', 'SUB-020', 'Emulsiones grasas, principalmente del tipo agua en aceite, incluidos los productos a base de emulsiones grasas mezcladas y/o aromatizados', 1, 20),
    ('CAT-03', 'SUB-021', 'Helados a base de agua elaborados con grasas vegetales.', 1, 21),
    ('CAT-04', 'SUB-022', 'Frutas congeladas', 3, 22),
    ('CAT-04', 'SUB-023', 'Frutas desecadas', 1, 23),
    ('CAT-04', 'SUB-024', 'Frutas en vinagre, aceite o salmuera', 1, 24),
    ('CAT-04', 'SUB-025', 'Frutas en conserva, enlatadas o en frascos (pasteurizadas)', 1, 25),
    ('CAT-04', 'SUB-026', 'Confituras, jaleas, mermeladas', 1, 26),
    ('CAT-04', 'SUB-027', 'Hortalizas, algas marinas, nueces y semillas congeladas', 2, 27),
    ('CAT-04', 'SUB-028', 'Hortalizas, algas marinas, nueces y semillas desecadas', 1, 28),
    ('CAT-04', 'SUB-029', 'Hortalizas, algas marinas, nueces y semillas en vinagre, aceite, salmuera o salsa de soja', 1, 29),
    ('CAT-04', 'SUB-030', 'Hortalizas, algas marinas, nueces y semillas en conserva, en latas o frascos (pasteurizadas) o en bolsas de esterilización', 1, 30),
    ('CAT-04', 'SUB-031', 'Purés y preparados para untar elaborados con hortalizas (incluidos hongos y setas, raíces y tubérculos, legumbres y leguminosas, incluyendo el maní).', NULL, 31),
    ('CAT-04', 'SUB-032', 'Pulpas y preparados de hortalizas', NULL, 32),
    ('CAT-04', 'SUB-033', 'Productos a base de hortalizas fermentadas, excluidos los productos fermentados de soja', NULL, 33),
    ('CAT-05', 'SUB-034', 'Productos de cacao y chocolate, incluidos los productos de imitación y los sucedáneos del chocolate', 1, 34),
    ('CAT-05', 'SUB-035', 'Dulces incluidos los caramelos duros y blandos, los turrones, etc.', 1, 35),
    ('CAT-05', 'SUB-036', 'Goma de mascar', 1, 36),
    ('CAT-05', 'SUB-037', 'Decoraciones (p. ej. para productos de pastelería fina), revestimientos (que no sean de fruta) y salsas dulces', 1, 37),
    ('CAT-06', 'SUB-038', 'Granos enteros, triturados o en copos, incluido el arroz', 1, 38),
    ('CAT-06', 'SUB-039', 'Harinas y almidones', 1, 39),
    ('CAT-06', 'SUB-040', 'Cereales para el desayuno, incluidos los copos de avena', 1, 40),
    ('CAT-06', 'SUB-041', 'Pastas y fideos frescos y productos análogos', 1, 41),
    ('CAT-06', 'SUB-042', 'Pastas y fideos deshidratados y productos análogos', 1, 42),
    ('CAT-06', 'SUB-043', 'Pastas y fideos precocidos y productos análogos', 1, 43),
    ('CAT-06', 'SUB-044', 'Mezclas batidas para rebozar (p. ej. para empanar o rebozar pescado o carne de aves de corral)', 1, 44),
    ('CAT-06', 'SUB-045', 'Productos a base de arroz precocidos o elaborados, incluidas las tortas de arroz (sólo del tipo oriental)', 1, 45),
    ('CAT-06', 'SUB-046', 'Productos a base de soja (excluidos aderezos y condimentos a base de soja)', 1, 46),
    ('CAT-06', 'SUB-047', 'Cuajada de soja deshidratada', NULL, 47),
    ('CAT-06', 'SUB-048', 'Soja fermentada', NULL, 48),
    ('CAT-07', 'SUB-049', 'Pan y productos de panadería ordinaria', 1, 49),
    ('CAT-07', 'SUB-050', 'Productos de panadería fina (dulces, salados, aromatizados) y mezclas', 1, 50),
    ('CAT-08', 'SUB-051', 'Crudo no intacto', 3, 51),
    ('CAT-08', 'SUB-052', 'Crudo intacto', 3, 52),
    ('CAT-08', 'SUB-053', 'Procesado térmicamente - Comercialmente estéril', 1, 53),
    ('CAT-08', 'SUB-054', 'No tratado térmicamente - Estable a temperatura ambiente', 2, 54),
    ('CAT-08', 'SUB-055', 'Tratado térmicamente - Estable a temperatura ambiente', 1, 55),
    ('CAT-08', 'SUB-056', 'Completamente cocido - No estable a temperatura ambiente', 1, 56),
    ('CAT-08', 'SUB-057', 'Tratado térmico parcial (sin alcanzar la letalidad) - No estable a temperatura ambiente', 2, 57),
    ('CAT-09', 'SUB-058', 'Huevos frescos', 3, 58),
    ('CAT-09', 'SUB-059', 'Productos líquidos a base de huevo pasteurizado', 1, 59),
    ('CAT-09', 'SUB-060', 'Productos congelados a base de huevo pasteurizado', 1, 60),
    ('CAT-09', 'SUB-061', 'Productos a base de huevo en polvo y/o cuajados por calor', 1, 61),
    ('CAT-09', 'SUB-062', 'Huevos en conserva, incluidos los huevos en álcali, salados y envasados', 2, 62),
    ('CAT-10', 'SUB-063', 'Azúcares refinados y en bruto', 1, 63),
    ('CAT-10', 'SUB-064', 'Soluciones azucaradas y jarabes, también azúcares (parcialmente) invertidos, incluida la melaza', 1, 64),
    ('CAT-10', 'SUB-065', 'Otros azúcares y jarabes (por ej. xilosa, jarabe de arce y revestimientos de azúcar)', 1, 65),
    ('CAT-10', 'SUB-066', 'Miel', 1, 66),
    ('CAT-10', 'SUB-067', 'Edulcorantes de mesa, incluidos los que contienen edulcorantes de gran intensidad', 1, 67),
    ('CAT-11', 'SUB-068', 'Sal y sucedáneos de la sal', 1, 68),
    ('CAT-11', 'SUB-069', 'Hierbas aromáticas, especias, aderezos y condimentos (p. ej. el aderezo para fideos instantáneos)', 1, 69),
    ('CAT-11', 'SUB-070', 'Vinagres', 1, 70),
    ('CAT-11', 'SUB-071', 'Mostazas', 1, 71),
    ('CAT-11', 'SUB-072', 'Sopas y caldos', 1, 72),
    ('CAT-11', 'SUB-073', 'Salsas y productos análogos', 1, 73),
    ('CAT-11', 'SUB-074', 'Levadura y productos similares', 1, 74),
    ('CAT-11', 'SUB-075', 'Aderezos y condimentos a base de soja', 1, 75),
    ('CAT-11', 'SUB-076', 'Productos proteínicos distintos a los de soja', 1, 76),
    ('CAT-12', 'SUB-077', 'Preparados para lactantes líquidos', 3, 77),
    ('CAT-12', 'SUB-078', 'Preparados para lactantes en polvo', 3, 78),
    ('CAT-12', 'SUB-079', 'Preparados de continuación líquidos', 3, 79),
    ('CAT-12', 'SUB-080', 'Preparados de continuación en polvo', 3, 80),
    ('CAT-12', 'SUB-081', 'Preparados para usos medicinales específicos destinados a los lactantes líquidos', 1, 81),
    ('CAT-12', 'SUB-082', 'Preparados para usos medicinales específicos destinados a los lactantes en polvo', 1, 82),
    ('CAT-12', 'SUB-083', 'Alimentos complementarios para lactantes y niños pequeños sólidos (polvos y granulados)', 1, 83),
    ('CAT-12', 'SUB-084', 'Alimentos complementarios para lactantes y niños pequeños semisólidos (compotas)', 1, 84),
    ('CAT-12', 'SUB-085', 'Alimentos dietéticos para usos medicinales especiales (excluidos los productos de preparados para lactantes, preparados de continuación y preparados para usos medicinales especiales destinados a los lactantes)', 1, 85),
    ('CAT-12', 'SUB-086', 'Preparados dietéticos para adelgazamiento y control del peso', 3, 86),
    ('CAT-12', 'SUB-087', 'Alimentos dietéticos (complementos alimenticios para usos dietéticos), excluidos los indicados en las categorías previas', 3, 87),
    ('CAT-13', 'SUB-088', 'Aguas', 1, 88),
    ('CAT-13', 'SUB-089', 'Jugos y néctares de frutas y hortalizas tratados térmicamente', 1, 89),
    ('CAT-13', 'SUB-090', 'Jugos artesanales (no tratados térmicamente)', 3, 90),
    ('CAT-13', 'SUB-091', 'Bebidas a base de agua aromatizadas, incluidas las bebidas para deportistas, bebidas electrolíticas y bebidas con partículas añadidas', 1, 91),
    ('CAT-13', 'SUB-092', 'Café, sucedáneos del café, té, infusiones de hierbas y otras bebidas calientes a base de cereales y granos, excluido el cacao', 1, 92),
    ('CAT-13', 'SUB-093', 'Cerveza y bebidas a base de malta', 1, 93),
    ('CAT-13', 'SUB-094', 'Sidra y sidra de pera', 1, 94),
    ('CAT-13', 'SUB-095', 'Vinos de uva', 1, 95),
    ('CAT-13', 'SUB-096', 'Vinos (distintos de los de uva)', 1, 96),
    ('CAT-13', 'SUB-097', 'Aguamiel', 1, 97),
    ('CAT-13', 'SUB-098', 'Licores destilados que contengan más de un 15 por ciento de alcohol', 1, 98),
    ('CAT-13', 'SUB-099', 'Bebidas alcohólicas aromatizadas (p. ej. cerveza, vino y bebidas espirituosas tipo refresco, refrescos con bajo contenido de alcohol)', 1, 99),
    ('CAT-14', 'SUB-100', 'Aperitivos a base de patatas (papas), cereales, harina o almidón (derivados de raíces y tubérculos, legumbres y leguminosas)', 1, 100),
    ('CAT-14', 'SUB-101', 'Nueces elaboradas, incluidas las nueces revestidas y mezclas de nueces (p. ej. con frutas secas)', 1, 101),
    ('CAT-16', 'SUB-103', 'Postres a base de leche', 1, 103),
    ('CAT-16', 'SUB-104', 'Postres a base de huevo', 1, 104),
    ('CAT-16', 'SUB-105', 'Postres a base de grasas, excluidos los postres lácteos (como pudines, yogur aromatizado o con fruta)', 1, 105),
    ('CAT-16', 'SUB-106', 'Postres a base de cereales y almidón (p. ej. pudines de arroz, pudines de yuca)', 1, 106),
    ('CAT-17', 'SUB-107', 'Pescado, filetes de pescado y productos pesqueros congelados, incluidos moluscos, crustáceos y equinodermos', 2, 107),
    ('CAT-17', 'SUB-108', 'Pescado, filetes de pescado y productos pesqueros rebozados congelados, incluidos moluscos, crustáceos y equinodermos', 2, 108),
    ('CAT-17', 'SUB-109', 'Productos pesqueros picados, amalgamados (mezclados) y congelados, incluidos moluscos, crustáceos y equinodermos', 2, 109),
    ('CAT-17', 'SUB-110', 'Pescado y productos pesqueros cocidos, incluidos moluscos, crustáceos y equinodermos', 1, 110),
    ('CAT-17', 'SUB-112', 'Pescado y productos pesqueros ahumados, desecados, fermentados y/o salados, incluidos moluscos, crustáceos y equinodermos', 2, 112),
    ('CAT-17', 'SUB-113', 'Pescado y productos pesqueros marinados y/o en gelatina, incluidos moluscos, crustáceos y equinodermos', 2, 113),
    ('CAT-17', 'SUB-114', 'Sucedáneos de salmón, caviar y otros productos pesqueros a base de huevas', 2, 114),
    ('CAT-17', 'SUB-115', 'Pescado y productos pesqueros (incluidos los moluscos, crustáceos y equinodermos) en conserva, con inclusión de los enlatados y fermentados', 1, 115)
) AS value(categoria_codigo, codigo, nombre, nivel_riesgo, orden)
JOIN "SIGERSA"."CATEGORIA_ALIMENTO" AS category ON category.codigo = value.categoria_codigo
ON CONFLICT (categoria_alimento_id, codigo) DO NOTHING;

COMMIT;
