BEGIN;

ALTER TABLE "SIGERSA"."SOLICITUD"
    DROP CONSTRAINT IF EXISTS "CK_SOLICITUD_ENVIO",
    DROP CONSTRAINT IF EXISTS "CK_SOLICITUD_ESTADO";

UPDATE "SIGERSA"."SOLICITUD"
   SET estado = 'PENDIENTE_ASIGNACION'
 WHERE estado = 'ENVIADA';

ALTER TABLE "SIGERSA"."SOLICITUD"
    ADD CONSTRAINT "CK_SOLICITUD_ESTADO"
        CHECK (estado IN ('BORRADOR', 'PENDIENTE_ASIGNACION', 'CANCELADA', 'RECHAZADA')),
    ADD CONSTRAINT "CK_SOLICITUD_ENVIO"
        CHECK (estado <> 'PENDIENTE_ASIGNACION' OR (numero IS NOT NULL AND enviada_en IS NOT NULL));

COMMIT;
