BEGIN;

ALTER TABLE "SIGERSA"."INFORME_VERSION"
    ADD COLUMN IF NOT EXISTS verification_token varchar(64);

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_INFORME_VERSION_VERIFICATION_TOKEN"
    ON "SIGERSA"."INFORME_VERSION" (verification_token)
    WHERE verification_token IS NOT NULL;

ALTER TABLE "SIGERSA"."INFORME_VERSION"
    DROP CONSTRAINT IF EXISTS "CK_INFORME_VERSION_VERIFICATION_TOKEN";

ALTER TABLE "SIGERSA"."INFORME_VERSION"
    ADD CONSTRAINT "CK_INFORME_VERSION_VERIFICATION_TOKEN"
    CHECK (verification_token IS NULL OR verification_token ~ '^[0-9a-f]{48}$');

COMMIT;
