<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-SIGERSA.Worker-588dbb8e-9c3b-4de7-bfd0-4909fd00f222</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIGERSA.Application\SIGERSA.Application.csproj" />
    <ProjectReference Include="..\SIGERSA.Infrastructure\SIGERSA.Infrastructure.csproj" />
  </ItemGroup>
</Project>
