<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SIGERSA.Application\SIGERSA.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.12" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="PuppeteerSharp" Version="25.10.0" />
    <PackageReference Include="Supabase" Version="8.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Reports\Assets\sigersa-logo.png" />
    <EmbeddedResource Include="Reports\Assets\digemaps-logo.png" />
    <EmbeddedResource Include="Reports\Assets\Poppins-Regular.ttf" />
    <EmbeddedResource Include="Reports\Assets\Poppins-SemiBold.ttf" />
  </ItemGroup>

</Project>
